version: 2

sources:
  - name: erp
    description: Modelo com as tabelas fonte - raw tables
    database: fea24_4 
    schema: raw_adventure_works
    tables:
      - name: ADDRESS
        description: Tabela dos endereços
        columns:
          - name: ADDRESSID
            description: Chave primaria dos endereços
            tests:
              - not_null
          - name: STATEPROVINCEID
            description: Chave estrangeira da tabela dos estados
            tests:
              - not_null
              - relationships:
                  to: ref('src_erp__STATEPROVINCE')
                  field: STATEPROVINCEID
      - name: ADDRESSTYPE
        description: Tabela dos tipos de endereços
        columns:
          - name: ADDRESSTYPEID
            description: Chave primária dos tipos de endereço
            tests:
              - not_null
      - name: BUSINESSENTITYADDRESS
        description: Tabela das entidades de negócio com as chaves dos endereços
        columns:
          - name: BUSINESSENTITYID
            description: Chave estrangeira da pessoa
            tests:
              - not_null
              - relationships:
                  to: ref('src_erp__PERSON')
                  field: BUSINESSENTITYID
          - name: ADDRESSID
            description: Chave estrangeira do endereço
            tests:
              - not_null
              - relationships:
                  to: ref('src_epr__ADDRESS')
                  field: ADDRESSID
          - name: ADDRESSTYPEID
            description: Chave estrangeira do endereço
            tests:
              - not_null
              - relationships:
                  to: ref('src_erp__ADDRESSTYPE')
                  field: ADDRESSTYPEID
      - name: BUSINESSENTITYCONTACT
        description: Tabela das entidades de negócio com as chaves das pessoas e dos tipos de contato
        columns:
          - name: BUSINESSENTITYID
            description: Chave estrangeira das lojas
            tests:
              - relationships:
                  to: ref('src_erp__STORE')
                  field: BUSINESSENTITYID
          - name: PERSONID
            description: Chave estrangeira das pessoas
            tests:
              - relationships:
                  to: ref('src_erp__PERSON')
                  field: BUSINESSENTITYID
          - name: CONTACTTYPEID
            description: Chave estrangeira do tipo de contato
            tests:
              - not_null
              - relationships:
                  to: ref('src_erp__CONTACTTYPE')
                  field: CONTACTTYPEID    
      - name: CONTACTTYPE
        description: Tabela dos tipos de contatos
        columns:
          - name: CONTACTTYPEID
            description: Chave primaria dos tipos de contato
            tests:
              - not_null
      - name: COUNTRYREGION
        description: Tabela dos países
        columns:
          - name: COUNTRYREGIONCODE
            description: Chave primaria dos países
            tests:
              - not_null
      - name: CREDITCARD
        description: Tabela dos cartões de crédito
        columns:
          - name: CREDITCARDID
            description: Chave primaria dos cartões de crédito
            tests:
              - not_null
      - name: CUSTOMER
        description: Tabela dos clientes
        columns:
          - name: CUSTOMERID
            description: Chave primaria dos clientes
            tests:
              - not_null
          - name: PERSONID
            description: Chave estrangeira das pessoas
            tests:
              - not_null
              - relationships:
                  to: ref('src_erp__PERSON')
                  field: BUSINESSENTITYID
          - name: STOREID
            description: Chave estrangeira das lojas
            tests:
              - not_null
              - relationships:
                  to: ref('src_erp__STORE')
                  field: BUSINESSENTITYID
      - name: DEPARTMENT
        description: Tabela dos setores dos funcionários
        columns:
          - name: DEPARTMENTID
            description: Chave primaria dos departamentos
            tests:
              - not_null
      - name: EMPLOYEE
        description: Tabela dos funcionários
        columns:
          - name: BUSINESSENTITYID
            description: Chave primaria dos funcionários
            tests:
              - not_null
      - name: EMPLOYEEDEPARTMENTHISTORY
        description: Tabela dos funcionários com as chaves dos departamentos
        columns:
          - name: BUSINESSENTITYID
            description: Chave estrangeira dos funcionários
            tests:
              - not_null
              - relationships:
                  to: ref('src_erp__EMPLOYEE')
                  field: BUSINESSENTITYID
          - name: DEPARTMENTID
            description: Chave estrangeira dos departamentos
            tests:
              - not_null
              - relationships:
                  to: ref('src_erp__EMPLOYEE')
                  field: DEPARTMENTID
          - name: SHIFTID
            description: Chave estrangeira dos turnos
            tests:
              - not_null
              - relationships:
                  to: ref('src_erp__EMPLOYEE')
                  field: SHIFTID
      - name: PERSON
        description: Tabela das pessoas
        columns:
          - name: BUSINESSENTITYID
            description: Chave primaria das pessoas
            tests:
              - not_null
      - name: PERSONCREDITCARD
        description: Tabela dos cartões das pessoas
        columns:
          - name: BUSINESSENTITYID
            description: Chave estrangeira das pessoas
            tests:
              - not_null
              - relationships:
                  to: ref('src_erp__PERSON')
                  field: BUSINESSENTITYID
          - name: CREDITCARDID
            description: Chave estrangeira das pessoas
            tests:
              - not_null
              - relationships:
                  to: ref('src_erp__CREDITCARD')
                  field: CREDITCARDID
      - name: PRODUCT
        description: Tabela dos produtos
        columns:
          - name: PRODUCTID
            description: Chave primaria dos produtos
            tests:
              - not_null
          - name: PRODUCTSUBCATEGORYID
            description: Chave estrangeira das subcategorias
            tests:
              - not_null
              - relationships:
                  to: ref('src_erp__PRODUCTSUBCATEGORY')
                  field: PRODUCTSUBCATEGORYID
          - name: PRODUCTMODELID
            description: Chave estrangeira das pessoas
            tests:
              - not_null
              - relationships:
                  to: ref('src_erp__PRODUCTMODEL')
                  field: PRODUCTMODELID
      - name: PRODUCTCATEGORY
        description: Tabela das categorias dos produtos
        columns:
          - name: PRODUCTCATEGORYID
            description: Chave primaria das categorias dos produtos
            tests:
              - not_null
      - name: PRODUCTMODEL
        description: Tabela com os modelos dos produtos
        columns:
          - name: PRODUCTMODELID
            description: Chave primaria dos modelos dos produtos
            tests:
              - not_null
      - name: PRODUCTSUBCATEGORY
        description: Tabela das subcategorias dos produtos
        columns:
          - name: PRODUCTSUBCATEGORYID
            description: Chave primaria das subcategorias dos produtos
            tests:
              - not_null
          - name: PRODUCTCATEGORYID
            description: Chave estrangeira das categorias dos produtos
            tests:
              - not_null
              - relationships:
                  to: ref('src_erp__PRODUCTCATEGORY')
                  field: PRODUCTCATEGORYID
      - name: SALESORDERDETAIL
        description: Tabela com os itens dos pedidos
        columns:
          - name: SALESORDERDETAILID
            description: Chave primaria dos itens dos pedidos
            tests:
              - not_null
          - name: SALESORDERID
            description: Chave estrangeira dos pedidos
            tests:
              - not_null
              - relationships:
                  to: ref('src_erp__SALESORDERHEADER')
                  field: SALESORDERID
          - name: PRODUCTID
            description: Chave estrangeira dos produtos
            tests:
              - not_null
              - relationships:
                  to: ref('src_erp__PRODUCT')
                  field: PRODUCTID
          - name: SPECIALOFFERID
            description: Chave estrangeira das ofertas
            tests:
              - not_null
              - relationships:
                  to: ref('src_erp__SPECIALOFFER')
                  field: SPECIALOFFERID
      - name: SALESORDERHEADER
        description: Tabela dos cabeçalhos dos pedidos
        columns:
          - name: SALESORDERID
            description: Chave primaria dos pediso
            tests:
              - not_null
          - name: CUSTOMERID
            description: Chave estrangeira dos clientes
            tests:
              - not_null
              - relationships:
                  to: ref('src_erp__CUSTOMER')
                  field: CUSTOMERID
          - name: SALESPERSONID
            description: Chave estrangeira dos vendedores
            tests:
              - not_null
              - relationships:
                  to: ref('src_erp__SALESPERSON')
                  field: SALESPERSONID
          - name: SHIPMETHODID
            description: Chave estrangeira das transportadoras
            tests:
              - not_null
              - relationships:
                  to: ref('src_erp__SHIPMETHOD')
                  field: SHIPMETHODID
          - name: CREDITCARDID
            description: Chave estrangeira dos cartões de crédito
            tests:
              - not_null
              - relationships:
                  to: ref('src_erp__CREDITCARD')
                  field: CREDITCARDID
          - name: SHIPTOADDRESSID
            description: Chave estrangeira dos endereços
            tests:
              - not_null
              - relationships:
                  to: ref('src_epr__ADDRESS')
                  field: ADDRESSID
      - name: SALESORDERHEADERSALESREASON
        description: Tabela dos pedidos com as chaves dos motivos de venda
        columns:
          - name: 
            description: Chave primaria dos 
            tests:
              - not_null
      - name: SALESPERSON
        description: Tabela dos vendedores
        columns:
          - name: 
            description: Chave primaria dos 
            tests:
              - not_null
      - name: SALESREASON
        description: Tabela dos motivos de venda
        columns:
          - name: 
            description: Chave primaria dos 
            tests:
              - not_null
      - name: SALESTERRITORYHISTORY
        description: Tabela dos endereços da venda dos pedidos ao longo do tempo
        columns:
          - name: 
            description: Chave primaria dos 
            tests:
              - not_null
      - name: SHIFT
        description: Tabela dos turnos
        columns:
          - name: 
            description: Chave primaria dos 
            tests:
              - not_null
      - name: SHIPMETHOD
        description: Tabela dos métodos de envio
        columns:
          - name: 
            description: Chave primaria dos 
            tests:
              - not_null
      - name: SPECIALOFFER
        description: Tabela das ofertas
        columns:
          - name: 
            description: Chave primaria dos 
            tests:
              - not_null
      - name: SPECIALOFFERPRODUCT
        description: Tabela das ofestas com as chaves dos produtos
        columns:
          - name: 
            description: Chave primaria dos 
            tests:
              - not_null
      - name: STATEPROVINCE
        description: Tabela dos estados
        columns:
          - name: 
            description: Chave primaria dos 
            tests:
              - not_null
      - name: STORE
        description: Tabela das lojas
        columns:
          - name: 
            description: Chave primaria dos 
            tests:
              - not_null
      - name: UNITMEASURE
        description: Tabela das unidades de medida
        columns:
          - name: 
            description: Chave primaria dos 
            tests:
              - not_null
      - name: VENDOR
        description: Tabela das plataformas de venda
        columns:
          - name: 
            description: Chave primaria dos 
            tests:
              - not_null
